# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir httpx mcp

# Copy application code
COPY . /app

# Default command
CMD ["python", "weather_server.py"]
